"""phase_1_ingestion_and_deduplication

Revision ID: f883ccb34a09
Revises: d7db50389b28
Create Date: 2026-09-05 16:32:23.399683+00:00

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f883ccb34a09"
down_revision: Union[str, Sequence[str], None] = "d7db50389b28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("business_id", sa.String(length=64), nullable=False),
        sa.Column("platform", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_fetched", sa.Integer(), nullable=False),
        sa.Column("records_normalized", sa.Integer(), nullable=False),
        sa.Column("records_inserted", sa.Integer(), nullable=False),
        sa.Column("records_skipped", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingestion_jobs_business_id"), "ingestion_jobs", ["business_id"], unique=False)
    op.create_index(op.f("ix_ingestion_jobs_platform"), "ingestion_jobs", ["platform"], unique=False)
    op.create_index(op.f("ix_ingestion_jobs_status"), "ingestion_jobs", ["status"], unique=False)
    op.create_table(
        "platform_connections",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("business_id", sa.String(length=64), nullable=False),
        sa.Column("platform", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("credentials", sa.JSON(), nullable=False),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_fetched", sa.Integer(), nullable=False),
        sa.Column("records_inserted", sa.Integer(), nullable=False),
        sa.Column("records_skipped", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("cursor", sa.String(length=255), nullable=True),
        sa.Column("rate_limit_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "platform", name="uq_business_platform_connection"),
    )
    op.create_index(op.f("ix_platform_connections_business_id"), "platform_connections", ["business_id"], unique=False)
    op.create_index(op.f("ix_platform_connections_platform"), "platform_connections", ["platform"], unique=False)
    with op.batch_alter_table("mentions") as batch_op:
        batch_op.add_column(sa.Column("content_hash", sa.String(length=64), nullable=True))
        batch_op.alter_column("external_id", existing_type=sa.VARCHAR(length=255), nullable=False)
        batch_op.create_index(batch_op.f("ix_mentions_content_hash"), ["content_hash"], unique=False)
        batch_op.create_unique_constraint("uq_business_platform_external", ["business_id", "platform", "external_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mentions") as batch_op:
        batch_op.drop_constraint("uq_business_platform_external", type_="unique")
        batch_op.drop_index(batch_op.f("ix_mentions_content_hash"))
        batch_op.alter_column("external_id", existing_type=sa.VARCHAR(length=255), nullable=True)
        batch_op.drop_column("content_hash")
    op.drop_index(op.f("ix_platform_connections_platform"), table_name="platform_connections")
    op.drop_index(op.f("ix_platform_connections_business_id"), table_name="platform_connections")
    op.drop_table("platform_connections")
    op.drop_index(op.f("ix_ingestion_jobs_status"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_platform"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_business_id"), table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    # ### end Alembic commands ###
